with open("tests/test_query_service_client.py","r",encoding="utf-8") as f:
    c = f.read()
c = c.replace("list_dispatches -> GET /api/query","list_tasks -> GET /api/query")
c = c.replace("get("/api/query" in code","get(/api/query" in code")
c = c.replace("get_dispatch -> GET /api/query/{id}","get_statistics -> GET /api/query/statistics")
c = c.replace("get("/api/query/statistics" in code","get(/api/query/statistics" in code")
c = c.replace("create_dispatch -> GET /api/query/ranking/customers","get_customer_ranking -> GET /api/query/ranking/customers")
c = c.replace("get("/api/query/ranking/customers" in code","get(/api/query/ranking/customers" in code")
c = c.replace("update_dispatch -> GET /api/query/ranking/machines/{id}","get_machine_ranking -> GET /api/query/ranking/machines")
c = c.replace("get("/api/query/ranking/machines" in code","get(/api/query/ranking/machines" in code")
c = c.replace("delete_dispatch -> POST /api/query/export/{id}","export_excel -> POST /api/query/export")
c = c.replace("post("/api/query/export" in code","post(/api/query/export" in code")
c = c.replace("export_excel body 为空 dict","export_excel body 含 sort_by")
c = c.replace("update_dispatch u4ec5u63d0u4ea4u975e None direction","export_excel u4ec5u63d0u4ea4u975e None_id")
c = c.replace("update_dispatch u4ec5u63d0u4ea4u975e None dispatch_date","export_excel u4ec5u63d0u4ea4u975e None process_status")
c = c.replace("logger.info u4f7fu7528","logger.debug u4f7fu7528 only")
c = c.replace("logger.info","logger.debug")
c = c.replace("list_dispatches u4ec5u63d0u4ea4u975e None direction","list_tasks u4ec5u63d0u4ea4u975e None_id")
c = c.replace("if direction is not None","if_id is not None")
with open("tests/test_query_service_client.py","w",encoding="utf-8") as f:
    f.write(c)
print("Done")
