with open("tests/test_dispatch_service_client.py","r",encoding="utf-8") as f:c=f.read()
c=c.replace("DispatchService","QueryService")
c=c.replace("dispatch_service","query_service")
c=c.replace("Task 9.4","Task 10.4")
c=c.replace("dispatch_service.py","query_service.py")
c=c.replace('"list_dispatches"','"list_tasks"')
c=c.replace('"get_dispatch"','"get_statistics"')
c=c.replace('"create_dispatch"','"get_customer_ranking"')
c=c.replace('"update_dispatch"','"get_machine_ranking"')
c=c.replace('"delete_dispatch"','"export_excel"')
c=c.replace('GET /api/dispatch','GET /api/query')
c=c.replace('POST /api/dispatch','GET /api/query/ranking/customers')
c=c.replace('PUT /api/dispatch','GET /api/query/ranking/machines')
c=c.replace('DELETE /api/dispatch','POST /api/query/export')
c=c.replace('"process_status" not in code','"TrialTaskProcessStatus" not in source')
c=c.replace('"result_status" not in code','"TrialTaskResultStatus" not in source')
c=c.replace('"list_dispatches u4ec5u63d0u4ea4u975e None direction"','"list_tasks u4ec5u63d0u4ea4u975e None_id"')
c=c.replace('"if direction is not None:" in source','"if_id is not None:" in source')
c=c.replace('"list_dispatches u4ec5u63d0u4ea4u975e None task_id"','"list_tasks u4ec5u63d0u4ea4u975e None machine_model"')
c=c.replace('"if task_id is not None:" in source','"if machine_model is not None:" in source')
c=c.replace('"update_dispatch body','"export_excel body')
c=c.replace('"body: dict[str, Any] = {}" in source','"sort_by" in source')
c=c.replace('"update_dispatch u4ec5u63d0u4ea4u975e None direction"','"export_excel u4ec5u63d0u4ea4u975e None_id"')
c=c.replace('"update_dispatch u4ec5u63d0u4ea4u975e None dispatch_date"','"export_excel u4ec5u63d0u4ea4u975e None process_status"')
c=c.replace('"update_dispatch u4ec5u63d0u4ea4u975e None operator_id"','"export_excel u4ec5u63d0u4ea4u975e None result_status"')
with open("tests/test_query_service_client.py","w",encoding="utf-8") as f:f.write(c)
print("Done")