import re
with open('tests/test_dispatch_service_client.py', 'r', encoding='utf-8') as f:
    c = f.read()
c = c.replace('DispatchService', 'QueryService')
c = c.replace('dispatch_service', 'query_service')
c = c.replace('Task 9.4', 'Task 10.4')
c = c.replace('dispatch_service.py', 'query_service.py')
c = c.replace('"list_dispatches", "list_dispatches" in public_methods', '"list_tasks", "list_tasks" in public_methods')
c = c.replace('"get_dispatch", "get_dispatch" in public_methods', '"get_statistics", "get_statistics" in public_methods')
c = c.replace('"create_dispatch", "create_dispatch" in public_methods', '"get_customer_ranking", "get_customer_ranking" in public_methods')
c = c.replace('"update_dispatch", "update_dispatch" in public_methods', '"get_machine_ranking", "get_machine_ranking" in public_methods')
c = c.replace('"delete_dispatch", "delete_dispatch" in public_methods', '"export_excel", "export_excel" in public_methods')
c = c.replace('"list_dispatches u2192 GET /api/dispatch"', '"list_tasks u2192 GET /api/query"')
c = c.replace('""/api/dispatch"" in code', '""/api/query"" in code')
c = c.replace('"get_dispatch u2192 GET /api/dispatch/{id}"', '"get_statistics u2192 GET /api/query/statistics"')
c = c.replace('""/api/dispatch/{" in code', '""/api/query/statistics"" in code')
c = c.replace('"create_dispatch u2192 POST /api/dispatch"', '"get_customer_ranking u2192 GET /api/query/ranking/customers"')
c = c.replace('"post(""/api/dispatch"" in code', '""/api/query/ranking/customers"" in code')
c = c.replace('"update_dispatch u2192 PUT /api/dispatch/{id}"', '"get_machine_ranking u2192 GET /api/query/ranking/machines"')
c = c.replace('"put(" in code', '""/api/query/ranking/machines"" in code')
c = c.replace('"delete_dispatch u2192 DELETE /api/dispatch/{id}"', '"export_excel u2192 POST /api/query/export"')
c = c.replace('"delete(" in code', '"post(""/api/query/export"" in code')
c = c.replace('"process_status" not in code', '"TrialTaskProcessStatus" not in source')
c = c.replace('"result_status" not in code', '"TrialTaskResultStatus" not in source')
c = c.replace('"list_dispatches u4ec5u63d0u4ea4u975e None direction"', '"list_tasks u4ec5u63d0u4ea4u975e None_id"')
c = c.replace('"if direction is not None:" in source', '"if_id is not None:" in source')
c = c.replace('"list_dispatches u4ec5u63d0u4ea4u975e None task_id"', '"list_tasks u4ec5u63d0u4ea4u975e None machine_model"')
c = c.replace('"if task_id is not None:" in source', '"if machine_model is not None:" in source')
c = c.replace('"update_dispatch body', '"export_excel body')
c = c.replace('"body: dict[str, Any] = {}" in source', '""_name" in source')
c = c.replace('"update_dispatch u4ec5u63d0u4ea4u975e None direction"', '"export_excel u4ec5u63d0u4ea4u975e None_id"')
c = c.replace('"update_dispatch u4ec5u63d0u4ea4u975e None dispatch_date"', '"export_excel u4ec5u63d0u4ea4u975e None process_status"')
c = c.replace('"update_dispatch u4ec5u63d0u4ea4u975e None operator_id"', '"export_excel u4ec5u63d0u4ea4u975e None result_status"')
with open('tests/test_query_service_client.py', 'w', encoding='utf-8') as f:
    f.write(c)
print('Done')
