"""initial migration

Revision ID: eaeabd4d1c07
Revises: 
Create Date: 2026-07-03 15:49:57.730358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaeabd4d1c07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限编码（唯一，如 task:create）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色标识（唯一）'),
    sa.Column('display_name', sa.String(length=50), nullable=False, comment='角色显示名'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统内置角色（不可删除）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 密码哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='启用状态'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customers',
    sa.Column('company_name', sa.String(length=200), nullable=False, comment='公司名称'),
    sa.Column('contact', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('address', sa.Text(), nullable=True, comment='地址'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_customers_created_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_company_name', 'customers', ['company_name'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色 ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限 ID'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作人 ID'),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', name='actiontype'), nullable=False, comment='操作类型（create/update/delete/status_change）'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='操作对象类型'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='操作对象 ID'),
    sa.Column('changes', sa.JSON(), nullable=True, comment='变更内容（JSON）'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP 地址'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_logs_action', 'system_logs', ['action'], unique=False)
    op.create_index('ix_logs_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('ix_logs_user_id', 'system_logs', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色 ID'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_table('trial_tasks',
    sa.Column('task_no', sa.String(length=20), nullable=False, comment='任务编号 (TM202600001)'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='客户 ID'),
    sa.Column('requirement', sa.Text(), nullable=False, comment='加工要求'),
    sa.Column('tracking_no', sa.String(length=100), nullable=True, comment='快递单号'),
    sa.Column('sales_id', sa.Integer(), nullable=False, comment='销售 ID'),
    sa.Column('process_status', sa.Enum('CREATED', 'RECEIVED', 'GRINDING', 'DISPATCHED', 'CLOSED', name='trialtaskprocessstatus'), nullable=False, comment='流程状态（created/received/grinding/dispatched/closed）'),
    sa.Column('result_status', sa.Enum('PENDING', 'PASSED', 'FAILED', name='trialtaskresultstatus'), nullable=False, comment='结果状态（pending/passed/failed）'),
    sa.Column('destination', sa.Enum('RETURNED_CUSTOMER', 'RETAINED_COMPANY', 'SCRAPPED', 'RETURNED_SALES', 'OTHER', name='destinationtype'), nullable=True, comment='工件去向（returned_customer/retained_company/scrapped/returned_sales/other）'),
    sa.Column('destination_date', sa.Date(), nullable=True, comment='工件去向日期'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='失败原因（result_status=failed 时填写）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    op.create_index('ix_trial_tasks_created_at', 'trial_tasks', ['created_at'], unique=False)
    op.create_index('ix_trial_tasks_customer_id', 'trial_tasks', ['customer_id'], unique=False)
    op.create_index('ix_trial_tasks_is_deleted', 'trial_tasks', ['is_deleted'], unique=False)
    op.create_index('ix_trial_tasks_process_status', 'trial_tasks', ['process_status'], unique=False)
    op.create_index('ix_trial_tasks_result_status', 'trial_tasks', ['result_status'], unique=False)
    op.create_index('ix_trial_tasks_sales_id', 'trial_tasks', ['sales_id'], unique=False)
    op.create_table('attachments',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联试磨任务 ID'),
    sa.Column('file_type', sa.Enum('IMAGE', 'DOCUMENT', 'CAD', 'VIDEO', name='filetype'), nullable=False, comment='附件类型（image/document/cad/video）'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（bytes）'),
    sa.Column('uploaded_by', sa.Integer(), nullable=False, comment='上传人 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['task_id'], ['trial_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_file_type', 'attachments', ['file_type'], unique=False)
    op.create_index('ix_attachments_task_id', 'attachments', ['task_id'], unique=False)
    op.create_table('dispatches',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联试磨任务 ID'),
    sa.Column('direction', sa.String(length=200), nullable=False, comment='去向描述'),
    sa.Column('dispatch_date', sa.DateTime(), nullable=False, comment='去向日期'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作人 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['trial_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('grinding_records',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联试磨任务 ID'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='试磨责任人 ID'),
    sa.Column('machine_type', sa.String(length=100), nullable=True, comment='试磨机型'),
    sa.Column('wheel_type', sa.String(length=100), nullable=True, comment='砂轮型号'),
    sa.Column('params', sa.Text(), nullable=True, comment='加工参数'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='工件领出时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('image_paths', sa.Text(), nullable=True, comment='试磨图片路径（JSON 数组）'),
    sa.Column('fail_reason', sa.Text(), nullable=True, comment='失败原因（result_status=failed 时填写）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['trial_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_grinding_machine_type', 'grinding_records', ['machine_type'], unique=False)
    op.create_index('ix_grinding_operator_id', 'grinding_records', ['operator_id'], unique=False)
    op.create_index('ix_grinding_start_time', 'grinding_records', ['start_time'], unique=False)
    op.create_table('inspection_records',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联试磨任务 ID'),
    sa.Column('report_path', sa.String(length=500), nullable=True, comment='检测报告文件路径'),
    sa.Column('accuracy', sa.String(length=100), nullable=True, comment='精度检测结果'),
    sa.Column('roughness', sa.String(length=100), nullable=True, comment='表面粗糙度检测结果'),
    sa.Column('result', sa.Enum('PASS', 'FAIL', name='inspectionresult'), nullable=True, comment='检测结论（pass / fail）'),
    sa.Column('inspector_id', sa.Integer(), nullable=True, comment='检测人 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['trial_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('notifications',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联试磨任务 ID'),
    sa.Column('type', sa.Enum('RECEIPT_DELAY', 'GRINDING_DELAY', 'REPORT_MISSING', name='notifytype'), nullable=False, comment='提醒类型（receipt_delay/grinding_delay/report_missing）'),
    sa.Column('message', sa.Text(), nullable=False, comment='提醒内容'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('target_user_id', sa.Integer(), nullable=False, comment='目标用户 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['trial_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_target_user', 'notifications', ['target_user_id'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_table('receipts',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联试磨任务 ID'),
    sa.Column('received_at', sa.DateTime(), nullable=False, comment='收件日期时间'),
    sa.Column('receiver_id', sa.Integer(), nullable=False, comment='收件人 ID'),
    sa.Column('image_paths', sa.Text(), nullable=True, comment='工件图片路径（JSON 数组）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人 ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记 (True=已删除)'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['trial_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_target_user', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('inspection_records')
    op.drop_index('ix_grinding_start_time', table_name='grinding_records')
    op.drop_index('ix_grinding_operator_id', table_name='grinding_records')
    op.drop_index('ix_grinding_machine_type', table_name='grinding_records')
    op.drop_table('grinding_records')
    op.drop_table('dispatches')
    op.drop_index('ix_attachments_task_id', table_name='attachments')
    op.drop_index('ix_attachments_file_type', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_trial_tasks_sales_id', table_name='trial_tasks')
    op.drop_index('ix_trial_tasks_result_status', table_name='trial_tasks')
    op.drop_index('ix_trial_tasks_process_status', table_name='trial_tasks')
    op.drop_index('ix_trial_tasks_is_deleted', table_name='trial_tasks')
    op.drop_index('ix_trial_tasks_customer_id', table_name='trial_tasks')
    op.drop_index('ix_trial_tasks_created_at', table_name='trial_tasks')
    op.drop_table('trial_tasks')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_logs_user_id', table_name='system_logs')
    op.drop_index('ix_logs_created_at', table_name='system_logs')
    op.drop_index('ix_logs_action', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_customers_company_name', table_name='customers')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
